### ISSUE TITLE
wait until socket is available 

### ISSUE THREAD

**Issue by groob** [kolide/osquery-go#50]
From @theopolis in slack:

> I’m seriousness, yes, there is lag between socket creation and socket availability. Your thrift wrapper should take care of this, C++ and python do it by waiting up to —timeout seconds, and retrying every 200ms

**Comment by leonjza** [comment]
For now, I handle this with a small loop:

```
for count < tries {

	if _, err := os.Stat(*socketPath); os.IsNotExist(err) {

		time.Sleep(time.Millisecond * 200)
		count++

		continue
	}
}
```

**Comment by groob** [comment]
This should really be fixed upstream by thrift since it asks for a timeout... 
https://github.com/kolide/osquery-go/blob/dc07ffdf186374c0a1328bb181e5f11d854508a2/transport/transport.go#L21

**Comment by groob** [comment]
Digging further it appears that timeout is propagated all the way to stdlib net.DialTimeout but it still fails:
https://github.com/apache/thrift/blob/d907cc92db5b93e699a4282e979d097ea863215a/lib/go/thrift/socket.go#L97

**Comment by theopolis** [comment]
Thanks for this!

That timeout (`Open`) is a time waiting for socket response. Our libraries should be implementing a timeout/retry check for the initial open as we race against the OS to make the socket available.
