### ISSUE TITLE
thrift git repo moved

### ISSUE THREAD

**Issue by groob** [kolide/osquery-go#52]
https://issues.apache.org/jira/projects/THRIFT/issues/THRIFT-4542?filter=allopenissues

It looks like `dep ensure -vendor-only` still works, but attempting to update it fails

```
dep ensure -update -v
Root project is "github.com/kolide/osquery-go"
 14 transitively valid internal packages
 5 external packages imported from 4 projects
(0)   ✓ select (root)
(1)	  ← no more versions of git.apache.org/thrift.git to try; begin backtrack
  ✗ solving failed

Solver wall times by segment:
  b-source-exists: 447.612396ms
  b-list-versions: 158.997027ms
      select-root:    387.594µs
            other:     82.197µs
         new-atom:     39.252µs

  TOTAL: 607.118466ms

Solving failure: failed to list versions for https://git.apache.org/thrift.git: fatal: repository 'https://git.apache.org/thrift.git/' not found
: exit status 128
```

**Comment by groob** [comment]
The apache project reverted the changes but it's only a temporary reversal. Keeping the issue open to track until the Jira ticket is resolved.

**Comment by jpeach** [comment]
I just tried to add `osquery-go` to a project that uses govendor, and found that the thrift repo is still not available on `git.apache.org`. Is there a new thrift import URL that could be used instead?

**Comment by groob** [comment]
Don't use govendor, or update the govendor pins to match the module file settings from here.

**Comment by jpeach** [comment]
I don't own the project, so the govendor part is out of my control :(

govendor isn't able to follow the redirect to clone the repo, so I'm not sure about the govendor pins suggestion (I'll go read docs for it)

```
$ govendor fetch -insecure github.com/kolide/osquery-go
# cd .; git clone git.apache.org/thrift /Users/jpeach/go/.cache/govendor/git.apache.org/thrift.git
fatal: repository 'git.apache.org/thrift' does not exist
Error: failed to create repo "git.apache.org/thrift" in "/Users/jpeach/go/.cache/govendor/git.apache.org/thrift.git" exit status 128
Failed to fetch package "git.apache.org/thrift.git/lib/go/thrift"
```

**Comment by jpeach** [comment]
FWIW, I manually cloned the new thrift repo into my vendor directory and govendor accepted that.

**Comment by directionless** [comment]
Fixed in https://github.com/kolide/osquery-go/pull/72
