### ISSUE TITLE
Results as map[string]interface{} rather then map[string]string

### ISSUE THREAD

**Issue by mickep76** [kolide/osquery-go#79]
Would it be possible to have response return the actual data type like a map[string]interface{} rather then have the value always be a string.

**Comment by zwass** [comment]
I believe the Thrift interface to osquery is providing us the values as strings. Perhaps we could add a helper function that attempts conversion to various types?

**Comment by mickep76** [comment]
I think if this is a design because of a protocol limitation then I would just close the ticket, converting values into another type is simple enough for anyone using it and it would also require knowledge of the underlying schema.

**Comment by directionless** [comment]
https://github.com/kolide/osquery-go/pull/77 is a draft of the inverse, and may or may not be interesting
