### ISSUE TITLE
Breaking change in Apache Thrift NewTSocketFromAddrTimeout

### ISSUE THREAD

**Issue by fightingmonk** [kolide/osquery-go#81]
This [commit](https://github.com/apache/thrift/commit/81334cd7345d3b5af165aa875b733a491f1fd5c7) to the Apache Thrift go library adds a socket timeout param to NewTSocketFromAddrTimeout(), which causes a fatal error when compiling **osquery-go** in `transport.go`.

~~~
# github.com/kolide/osquery-go/transport
/go/src/github.com/kolide/osquery-go/transport/transport.go:31:43: not enough arguments in call to thrift.NewTSocketFromAddrTimeout
	have (*net.UnixAddr, time.Duration)
	want (net.Addr, time.Duration, time.Duration)
~~~

I tested on Linux and OSX with go 1.11 and 1.14. Not sure if the Windows version is affected.

The simplest fix looks like using the same timeout value for both the connectTimeout and socketTimeout params, changing [transport.go#L31](https://github.com/kolide/osquery-go/blob/master/transport/transport.go#L31) from:

    trans := thrift.NewTSocketFromAddrTimeout(addr, timeout)

to:

    trans := thrift.NewTSocketFromAddrTimeout(addr, timeout, timeout)

I'm happy to open a PR for this if it looks reasonable.

**Comment by directionless** [comment]
Hrm. That commit isn't yet in a released version. So I'd expect module versioning to have handled it.

I wonder if they'll ever cut a new version

**Comment by fightingmonk** [comment]
I don't get the error when installing the osquery-go module itself, only when following the instructions in the README to build the [sample table extension](https://github.com/kolide/osquery-go/blob/master/README.md#creating-a-new-osquery-table). 

I'm not super familiar with dependency versioning in go; do the sample instructions need updated?

**Comment by zwass** [comment]
I think the instructions need updating. We expect that projects with osquery-go are using go modules, and that should keep the Thrift commit pinned to a specific version.

**Comment by fightingmonk** [comment]
@zwass Yeah, that looks like the answer. I created this `go.mod` file in the same dir as my extension and ran `go get`, and now it compiles cleanly.

```
require (
    github.com/kolide/osquery-go latest
)
```

**Comment by zwass** [comment]
Nevertheless it probably makes sense to upgrade the Thrift version and fix the breaking changes.

**Comment by amalone-scwx** [comment]
new release thrift release v0.13.0  4 days ago on May 26th, 2020...
