### ISSUE TITLE
Build C++ extentions

### ISSUE THREAD

**Issue by gitrepoact** [kolide/osquery-go#87]
Sorry to use this forum but does anyone have document detailing compiling C++ extension (all the documents provided by OSQuery not working) . Any help will be much appreciated.

**Comment by directionless** [comment]
This is not an osquery-go issue. The best place to get help is the [community slack instance](https://join.slack.com/t/osquery/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw).
